import { Activity, AreaChart, Atom, BarChart3, BatteryCharging, BatteryFull, Beaker, BlockQuote, Blocks, BookOpenCheck, Brain, Brackets, Calculator, Circle, CircleDot, Coil, Cpu, Divide, DivideCircle, DNA, Droplet, Droplets, Ellipsis, Equal, Factory, Flame, FlameKindling, Flask, FlaskConical, FlaskRound, FunctionSquare, Gem, GitBranch, Grid2x2, Grid3X3, Hammer, HardHat, HelpCircle, Infinity, LayoutGrid, LayoutList, Leaf, Layers3, LineChart, Link2, Martini, Magnet, MessageSquareCode, MoveDiagonal, MoveRight, Orbit, PackagePlus, Pill, PlugZap, Radar, Radiation, RefreshCcw, Ruler, SatelliteDish, Scale, ShieldHalf, ShoppingBasket, Shuffle, Sigma, SineWave, SquareFunction, Sun, Table, Target, TentTree, TestTube, Timer, Triangle, Undo2, WaveSquare, Waves, Wind, Zap, ZapOff,RotateCcw,ThermometerSun, Signal, Boxes, ListOrdered, Cube } from 'lucide-react';


// Get icon component for chapter
export const getChapterIcon = (chapter) => {
  const iconMap = {
  'Mathematics in Physics': Brackets,
  'Units and Dimensions': Ruler,
  'Motion In One Dimension': MoveRight,
  'Motion In Two Dimensions': MoveDiagonal,
  'Laws of Motion': Hammer,
  'Work Power Energy': BatteryCharging,
  'Center of Mass Momentum and Collision': CircleDot,
  'Rotational Motion': RotateCcw,
  'Gravitation': Orbit,
  'Mechanical Properties of Solids': HardHat,
  'Mechanical Properties of Fluids': Droplets,
  'Thermal Properties of Matter': ThermometerSun,
  'Thermodynamics': Flame,
  'Kinetic Theory of Gases': Wind,
  'Oscillations': Activity,
  'Waves and Sound': WaveSquare,
  'Electrostatics': Zap,
  'Capacitance': BatteryFull,
  'Current Electricity': PlugZap,
  'Magnetic Properties of Matter': Magnet,
  'Magnetic Effects of Current': Coil,
  'Electromagnetic Induction': ZapOff,
  'Alternating Current': RefreshCcw,
  'Electromagnetic Waves': Signal,
  'Ray Optics': Sun,
  'Wave Optics': Waves,
  'Dual Nature of Matter': Scale,
  'Atomic Physics': Atom,
  'Nuclear Physics': Radiation,
  'Semiconductors': Cpu,
  'Communication System': SatelliteDish,
  'Experimental Physics': FlaskConical,
  'Some Basic Concepts of Chemistry': FlaskRound,
  'Structure of Atom': Atom,
  'Classification of Elements and Periodicity in Properties': Table,
  'Chemical Bonding and Molecular Structure': Link2,
  'States of Matter': Droplets,
  'Thermodynamics (C)': Flame,
  'Chemical Equilibrium': Scale,
  'Ionic Equilibrium': DivideCircle,
  'Redox Reactions': BatteryCharging,
  'Hydrogen': Droplet,
  's Block Elements': Boxes,
  'p Block Elements (Group 13 & 14)': BlockQuote,
  'General Organic Chemistry': FlaskConical,
  'Hydrocarbons': FlameKindling,
  'Environmental Chemistry': Leaf,
  'Solid State': LayoutGrid,
  'Solutions': Beaker,
  'Electrochemistry': Zap,
  'Chemical Kinetics': Timer,
  'Surface Chemistry': Grid2x2,
  'General Principles and Processes of Isolation of Metals': Factory,
  'p Block Elements (Group 15, 16, 17 & 18)': Blocks,
  'd and f Block Elements': Gem,
  'Coordination Compounds': GitBranch,
  'Haloalkanes and Haloarenes': Flask,
  'Alcohols Phenols and Ethers': Martini,
  'Aldehydes and Ketones': ShieldHalf,
  'Carboxylic Acid Derivatives': FlaskConical,
  'Amines': Pill,
  'Biomolecules': DNA,
  'Polymers': PackagePlus,
  'Chemistry in Everyday Life': ShoppingBasket,
  'Practical Chemistry': TestTube,
  'Basic of Mathematics': BookOpenCheck,
  'Quadratic Equation': FunctionSquare,
  'Complex Number': Infinity,
  'Permutation Combination': Layers3,
  'Sequences and Series': ListOrdered,
  'Mathematical Induction': Brain,
  'Binomial Theorem': Sigma,
  'Trigonometric Ratios & Identities': Waves,
  'Trigonometric Equations': SineWave,
  'Straight Lines': LineChart,
  'Pair of Lines': LayoutList,
  'Circle': Circle,
  'Parabola': TentTree,
  'Ellipse': Ellipsis,
  'Hyperbola': Radar,
  'Limits': MoveDiagonal,
  'Mathematical Reasoning': MessageSquareCode,
  'Statistics': BarChart3,
  'Heights and Distances': Ruler,
  'Properties of Triangles': Triangle,
  'Sets and Relations': Brackets,
  'Matrices': Table,
  'Determinants': Grid2x2,
  'Inverse Trigonometric Functions': Undo2,
  'Functions': FunctionSquare,
  'Continuity and Differentiability': Shuffle,
  'Differentiation': Divide,
  'Application of Derivatives': SquareFunction,
  'Indefinite Integration': Calculator,
  'Definite Integration': Sigma,
  'Area Under Curves': AreaChart,
  'Differential Equations': Equal,
  'Vector Algebra': MoveRight,
  'Three Dimensional Geometry': Cube,
  'Linear Programming': LineChart,
  'Probability': HelpCircle,
  };
  
  return iconMap[chapter] || Grid3X3;
};

// Get icon component by name
export const getIconComponent = (iconName) => {
  const iconMap = {
    'Zap': Zap,
    'Activity': Activity,
    'Calculator': Calculator,
    'Grid3X3': Grid3X3
  };
  
  return iconMap[iconName] || Grid3X3;
};